### ISSUE TITLE
Question about 32+64

### ISSUE THREAD

**Issue by LIJIAQI1999** [nissmar/VoroMesh#1]
Hi, thanks for your great work! The idea is brilliant and inspiring!
May I ask about the meaning of VoroMesh32+64 in experiment part? What do 32 and 64 mean respectively?
Again, Thanks a lot!

**Comment by Regenerator** [comment]
Hi, thanks for your interest in our work! It means that the model was trained with SDF grids of both 32^3 and 64^3 resolutions as viable inputs.

**Comment by LIJIAQI1999** [comment]
> Hi, thanks for your interest in our work! It means that the model was trained with SDF grids of both 32^3 and 64^3 resolutions as viable inputs.

Got it! Thanks!
